/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DrawingMetadata = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'minutesSpent' : IDL.Nat,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const Profile = IDL.Record({ 'displayName' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteDrawing' : IDL.Func([IDL.Nat], [], []),
  'getAllDrawings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DrawingMetadata)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyDrawings' : IDL.Func([], [IDL.Vec(DrawingMetadata)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getTotalDrawings' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTotalMinutesSpent' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveDrawing' : IDL.Func([DrawingMetadata], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DrawingMetadata = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'minutesSpent' : IDL.Nat,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const Profile = IDL.Record({ 'displayName' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteDrawing' : IDL.Func([IDL.Nat], [], []),
    'getAllDrawings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DrawingMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyDrawings' : IDL.Func([], [IDL.Vec(DrawingMetadata)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getTotalDrawings' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTotalMinutesSpent' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveDrawing' : IDL.Func([DrawingMetadata], [], []),
  });
};

export const init = ({ IDL }) => { return []; };